import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import JotaiProvider from "@/components/Provider/Provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from "./menu";
import ModalPortal from "./modal-portal";
import { Toaster } from "react-hot-toast";

const matterFont = localFont({
	src: [
		{
			path: "../../public/fonts/matter-font/Matter-Regular.otf",
			weight: "400",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<title>Portfolio</title>
				<link rel="icon" href="/Favicon.svg" type="image/x-icon" />
			</head>
			<JotaiProvider>
				<body className={matterFont.className}>
					<div className="min-h-screen">
						<Navbar />
						<main>{children}</main>
					</div>
					<Footer />
					<Menu />
					<ModalPortal />
					<Toaster position="bottom-center" />
				</body>
			</JotaiProvider>
		</html>
	);
}
