import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "@/components/Footer";

const matterFont = localFont({
	src: [
		{
			path: "../fonts/matter-font/Matter-Regular.otf",
			weight: "400",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<title>Portfolio</title>
				<link rel="icon" href="/Favicon.svg" type="image/x-icon" />
			</head>
			<body className={matterFont.className}>
				<Navbar />
				<main className="relative min-h-screen">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
