import "./globals.css";
import type { Metadata } from "next";
import localFont from 'next/font/local'

const matterFont = localFont({
	src: [
		{
			path: "../fonts/matter-font/Matter-Regular.otf",
			weight: "400",
			style: "normal"
		}
	]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={matterFont.className}>{children}</body>
		</html>
	);
}
